version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:  
          command: |
            cd ./setup/org.epsilonlabs.modelflow.dependencies/ && ./download-dependencies.sh
      - run: mvn clean verify
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
          - releng/org.epsilonlabs.modelflow.updatesite/target/

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace latest /tmp/artifacts/updatesite.zip
          
         
workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build