version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - run: cd setup/org.epsilonlabs.modelflow.dependencies
      - run: ./download-dependencies.sh
      - run: cd ../..
      - maven/test
         