version: 2.0

jobs:
  install_deps:
    docker:
      - image: circleci/openjdk:stretch
    steps:
    - checkout
    - run: 
        name: install missing dependencies
        command: |
          echo $PWD
          cd ./setup/org.epsilonlabs.modelflow.dependencies/
          ./download-dependencies.sh
    - run: ./mvnw clean verify
         