version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  install_deps:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - run: echo pwd
      - run: echo ls
      - run: cd setup/org.epsilonlabs.modelflow.dependencies
      - run: ./download-dependencies.sh
      - run: cd ../..
workflows:
  maven_test:
    jobs:
      - install_deps
      - maven/test
         