version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:  
          command: |
            cd ./setup/org.epsilonlabs.modelflow.dependencies/ && ./download-dependencies.sh
      - run: mvn clean verify
      - persist_to_workspace:
          root: ./
          paths:
          - releng/org.epsilonlabs.modelflow.updatesite/target/*.zip
          - tests/org.epsilonlabs.modelflow.jacoco/target/site/jacoco-aggregate/

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Publish Release on GitHub"
          command: |
            mkdir /tmp/release
            cp ./releng/org.epsilonlabs.modelflow.updatesite/target/updatesite.zip /tmp/release/
            zip -r /tmp/release/jacoco.zip ./tests/org.epsilonlabs.modelflow.jacoco/target/site/jacoco-aggregate/
            label="latest"
            [[ -n "${CIRCLE_TAG}" ]] && latest=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate ${CIRCLE_BRANCH} /tmp/release  
         
workflows:
  version: 2
  publish:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
            



