version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - run: 
          command: |
            cd ./setup/org.epsilonlabs.modelflow.dependencies/
            ./download-dependencies.sh
            cd ../..
    
workflows:
  modelflow:
    jobs:
    - build
    - maven/test: 
        requires:
          - build
        command: '-X clean verify'
         