<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace" nsURI="http://eclipse.org/epsilon/modelflow/management/trace/1.0"
    nsPrefix="managementTrace">
  <eClassifiers xsi:type="ecore:EClass" name="EStringToObjectMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManagementTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//TaskTrace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskTrace">
    <eAnnotations source="exeed">
      <details key="classIcon" value="operation"/>
      <details key="label" value="return self.task.name + ' trace';"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eType="ecore:EClass http://eclipse.org/epsilon/modelflow/1.0#//Task"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//Trace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eAnnotations source="exeed">
      <details key="classIcon" value="transition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
        eType="#//Element" containment="true">
      <eAnnotations source="exeed">
        <details key="featureLabel" value="source"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//Element" containment="true">
      <eAnnotations source="exeed">
        <details key="featureLabel" value="return 'target';"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="ecore:EClass http://eclipse.org/epsilon/modelflow/1.0#//Resource"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" eSuperTypes="#//Element">
    <eAnnotations source="exeed">
      <details key="classIcon" value="model"/>
      <details key="label" value="return self.container.name + '::' + self.elementId;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementProperty" eSuperTypes="#//ModelElement">
    <eAnnotations source="exeed">
      <details key="classIcon" value="parameter"/>
      <details key="label" value="return self.container.name + '::' + self.elementId + '::' + self.property;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileElement" eSuperTypes="#//Element">
    <eAnnotations source="exeed">
      <details key="classIcon" value="text"/>
      <details key="label" value="return '@'+self.region.offset + ':' + self.region.length;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" eType="#//Region"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eAnnotations source="exeed">
      <details key="classIcon" value="object"/>
      <details key="label" value="return self.offset + ':' + self.length;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eAnnotations source="exeed">
      <details key="classIcon" value="link"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManagementOperation" eSuperTypes="#//Link">
    <eAnnotations source="exeed">
      <details key="classIcon" value="operation"/>
      <details key="label" value="return self.link + ':' + self.managementOperation;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managementOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eAnnotations source="exeed">
      <details key="classIcon" value="private"/>
      <details key="label" value="return self.key + '=' + self.value;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
</ecore:EPackage>
